### ISSUE TITLE
Add color mode

### ISSUE THREAD

**Issue by soxofaan** [soxofaan/duviz#9]
add option to use ANSI colors to draw bars instead of ASCII art style

**Comment by zivanfi** [comment]
First of all, thanks for duviz, I find it to be a very handy util to have on all remote computers with SSH access.

I see that the color mode feature is already working in the color-mode branch but not in the version available through pip. I really like this mode because even tough colors may be a too saturated due to the ANSI palette, it still provides the best visualization of the disk usage distribution in text mode.

While installing duviz from source is not significantly more complicated than pip install, this effort gets multiplied by the number of computers. Easy installation using pip is key to being able to quickly get it up and running on any remote machine. For this reason, would you please consider releasing this feature if you are content with it current state? Thanks!

**Comment by soxofaan** [comment]
Hi @zivanfi, thanks for reaching out.

I just released 3.1.1 to PyPI, so you should be able to pip install the latest version now. Please confirm that everything works as expected.

I'm going to close this issue for now. Further improvements to the color mode (prettier colors, configurable colors, ...) are for other tickets.

**Comment by zivanfi** [comment]
Hi, Thanks for pushing the release to PyPI, everything works perfectly!
